version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid overwriting node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASEURL=http://localhost:4001/api
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    command: sh -c "npm start"
    # run manually once, at the start: docker compose run frontend npm install
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=howard
    init: true
    command: sh -c "npm start"
    # run manually once, at the start: docker compose run frontend npm install
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
      - ./db/initdb.d:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=howard
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres-data:
